# libraries/AP_Observer/wscript
def configure(cfg):
    cfg.env.AP_LIBRARIES.append('AP_Observer')
    cfg.env.append_value('AP_MODULE_NAMES', 'AP_Observer')

def build(bld):
    bld.env.CXXFLAGS.append('-DAP_OBSERVER_REPLAY_TEST=1')
    bld.ap_library(
        name='AP_Observer',
        source=bld.srcnode.ant_glob('*.cpp'),
        includes='.',
        depends=[
            'AP_HAL',
            'AP_Vehicle',
            'AP_Motors',
            'AP_Param',
            'AP_Common',
            'AP_Math',
            'GCS_MAVLink',
            'Filter',
            'AP_InertialSensor',
            'RC_Channel',
            'AP_Logger',
        ],
        cxxflags=['-Wno-unused-parameter', '-DAP_OBSERVER_REPLAY_TEST=1']  # 必要に応じて警告抑制
    )

    bld.recurse('examples/RLS_CSV_Replay')

